name: badminton_scrape

on:
  schedule:
    - cron: '0 */4 * * *'  # every 4th hour



jobs:
  billionaires_scrape:
    runs-on: macos-latest
    env:
      ATLAS_BERITA: ${{ secrets.ATLAS_BERITA }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
    steps:
      - name: Start time
        run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)' 
      - name: Install tidyverse package
        run: Rscript -e 'install.packages("tidyverse", dependencies = TRUE)'
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Scrape data 
        run: Rscript scrape.R
